//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinguaHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data.ini")]
        public string DataPath {
            get {
                return ((string)(this["DataPath"]));
            }
            set {
                this["DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DarkTheme {
            get {
                return ((bool)(this["DarkTheme"]));
            }
            set {
                this["DarkTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReverseOrderHisroty {
            get {
                return ((bool)(this["ReverseOrderHisroty"]));
            }
            set {
                this["ReverseOrderHisroty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSortByDate {
            get {
                return ((bool)(this["AutoSortByDate"]));
            }
            set {
                this["AutoSortByDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OALDLoginOnStart {
            get {
                return ((bool)(this["OALDLoginOnStart"]));
            }
            set {
                this["OALDLoginOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HistoryBackupPath {
            get {
                return ((string)(this["HistoryBackupPath"]));
            }
            set {
                this["HistoryBackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tasks.docx")]
        public string TaskFilePath {
            get {
                return ((string)(this["TaskFilePath"]));
            }
            set {
                this["TaskFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OALDPass {
            get {
                return ((string)(this["OALDPass"]));
            }
            set {
                this["OALDPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OALDUser {
            get {
                return ((string)(this["OALDUser"]));
            }
            set {
                this["OALDUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.urbandictionary.com/define.php?term=")]
        public string Urban_URL {
            get {
                return ((string)(this["Urban_URL"]));
            }
            set {
                this["Urban_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string firstTabName {
            get {
                return ((string)(this["firstTabName"]));
            }
            set {
                this["firstTabName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#282828")]
        public string DarkBackground {
            get {
                return ((string)(this["DarkBackground"]));
            }
            set {
                this["DarkBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#dadada")]
        public string DarkForeground {
            get {
                return ((string)(this["DarkForeground"]));
            }
            set {
                this["DarkForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ForceLoadFromBrowse {
            get {
                return ((bool)(this["ForceLoadFromBrowse"]));
            }
            set {
                this["ForceLoadFromBrowse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sound audio_play_button pron-us icon-audio")]
        public string OALD_AudioButton_ID {
            get {
                return ((string)(this["OALD_AudioButton_ID"]));
            }
            set {
                this["OALD_AudioButton_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SpeakOnBrowsingOALD {
            get {
                return ((bool)(this["SpeakOnBrowsingOALD"]));
            }
            set {
                this["SpeakOnBrowsingOALD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToggleGoogleTheme(\"dark\");")]
        public string GoogleDarkThemeJS {
            get {
                return ((string)(this["GoogleDarkThemeJS"]));
            }
            set {
                this["GoogleDarkThemeJS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToggleGoogleTheme(\"light\");")]
        public string GoogleLightThemeJS {
            get {
                return ((string)(this["GoogleLightThemeJS"]));
            }
            set {
                this["GoogleLightThemeJS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"function ToggleGoogleTheme(desiredTheme) 
{
//alert(""OK"");
  var toggleClassName = 'q0yked';
  var toggleElements = document.getElementsByClassName(toggleClassName);

	if (toggleElements.length > 3) 
	{
		var darkModeToggle = toggleElements[3].children[0];
		var toggleText = darkModeToggle.innerText;

		var isDarkModeCurrentlyOn = toggleText.includes('On');
		var isLightModeCurrentlyOn = toggleText.includes('Off');

		if(desiredTheme === 'light' && !isLightModeCurrentlyOn)
		{
			localStorage.setItem('themeChange', 'lightPending');
			darkModeToggle.click();
		}
		else if(desiredTheme === 'dark' && !isDarkModeCurrentlyOn)
		{
			localStorage.setItem('themeChange', 'darkPending');
			darkModeToggle.click();
		}
	}
}
function checkThemeChange() {
  if (localStorage.getItem('themeChange') === 'lightPending') {
    // Clear the flag first to prevent an infinite loop.
    localStorage.removeItem('themeChange');
    
    // Then perform the second click.
    ToggleGoogleTheme('light');
  }
  else if (localStorage.getItem('themeChange') === 'darkPending')
  {
	  // Clear the flag first to prevent an infinite loop.
    localStorage.removeItem('themeChange');
    
    // Then perform the second click.
    ToggleGoogleTheme('dark');
  }
}

// Call this function on page load.
document.addEventListener('DOMContentLoaded', checkThemeChange);")]
        public string GoogleColorThemePrepareJS {
            get {
                return ((string)(this["GoogleColorThemePrepareJS"]));
            }
            set {
                this["GoogleColorThemePrepareJS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JScriptErrors.log")]
        public string JsLogPath {
            get {
                return ((string)(this["JsLogPath"]));
            }
            set {
                this["JsLogPath"] = value;
            }
        }
    }
}
