//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data.ini")]
        public string DataPath {
            get {
                return ((string)(this["DataPath"]));
            }
            set {
                this["DataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DarkTheme {
            get {
                return ((bool)(this["DarkTheme"]));
            }
            set {
                this["DarkTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ReverseOrderHisroty {
            get {
                return ((bool)(this["ReverseOrderHisroty"]));
            }
            set {
                this["ReverseOrderHisroty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSortByDate {
            get {
                return ((bool)(this["AutoSortByDate"]));
            }
            set {
                this["AutoSortByDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OALDLoginOnStart {
            get {
                return ((bool)(this["OALDLoginOnStart"]));
            }
            set {
                this["OALDLoginOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HistoryBackupPath {
            get {
                return ((string)(this["HistoryBackupPath"]));
            }
            set {
                this["HistoryBackupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tasks.docx")]
        public string TaskFilePath {
            get {
                return ((string)(this["TaskFilePath"]));
            }
            set {
                this["TaskFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("css\\dark.mode.css")]
        public string DarkCSSColorThemePath {
            get {
                return ((string)(this["DarkCSSColorThemePath"]));
            }
            set {
                this["DarkCSSColorThemePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OALDPass {
            get {
                return ((string)(this["OALDPass"]));
            }
            set {
                this["OALDPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OALDUser {
            get {
                return ((string)(this["OALDUser"]));
            }
            set {
                this["OALDUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("teach_email")]
        public string OALDUserID {
            get {
                return ((string)(this["OALDUserID"]));
            }
            set {
                this["OALDUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("teach_password")]
        public string OALDPassID {
            get {
                return ((string)(this["OALDPassID"]));
            }
            set {
                this["OALDPassID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("teach_btn-login")]
        public string OALDSubmitID {
            get {
                return ((string)(this["OALDSubmitID"]));
            }
            set {
                this["OALDSubmitID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.oxfordlearnersdictionaries.com/search/english/?q=")]
        public string OALD_URL {
            get {
                return ((string)(this["OALD_URL"]));
            }
            set {
                this["OALD_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://translate.google.am/?hl=en#view=home&op=translate&sl=en&tl=ru&text=")]
        public string GT_URL {
            get {
                return ((string)(this["GT_URL"]));
            }
            set {
                this["GT_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.urbandictionary.com/define.php?term=")]
        public string Urban_URL {
            get {
                return ((string)(this["Urban_URL"]));
            }
            set {
                this["Urban_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Google Translator")]
        public string GT_Name {
            get {
                return ((string)(this["GT_Name"]));
            }
            set {
                this["GT_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.oxfordlearnersdictionaries.com/account/login")]
        public string OALDPrepareURL {
            get {
                return ((string)(this["OALDPrepareURL"]));
            }
            set {
                this["OALDPrepareURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dictionary.cambridge.org/dictionary/english-russian/")]
        public string Cambridge_URL {
            get {
                return ((string)(this["Cambridge_URL"]));
            }
            set {
                this["Cambridge_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://en.wikipedia.org/wiki/")]
        public string Wiki_URL {
            get {
                return ((string)(this["Wiki_URL"]));
            }
            set {
                this["Wiki_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string firstTabName {
            get {
                return ((string)(this["firstTabName"]));
            }
            set {
                this["firstTabName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("onetrust-accept-btn-handler")]
        public string OALD_AcceptAllCookies_ID {
            get {
                return ((string)(this["OALD_AcceptAllCookies_ID"]));
            }
            set {
                this["OALD_AcceptAllCookies_ID"] = value;
            }
        }
    }
}
